### ISSUE TITLE
Chart should be taller

### ISSUE THREAD

**Issue by capaj** [michalskop/mandaty.cz#15]
this way it's too conflated together. Even if I use the zoom tool it's still hard to distinguish all the lines. Please make it taller. Or have a button to switch from tall to small.

**Comment by michalskop** [comment]
Jedna možnost: filtrování stran (pomocí menu se jménami stran vpravo)

**Comment by capaj** [comment]
a další je editace v tom jejich chart studiu, I tak bych to udelal vetsi.
